
package cn.djel.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "IHelloWorldService", targetNamespace = "http://service.djel.cn/", wsdlLocation = "http://localhost:8089/testWebService/services/HelloServices?wsdl")
public class IHelloWorldService
    extends Service
{

    private final static URL IHELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(cn.djel.service.IHelloWorldService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = cn.djel.service.IHelloWorldService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8089/testWebService/services/HelloServices?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8089/testWebService/services/HelloServices?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IHELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public IHelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloWorldService() {
        super(IHELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://service.djel.cn/", "IHelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort() {
        return super.getPort(new QName("http://service.djel.cn/", "IHelloWorldPort"), IHelloWorld.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloWorld
     */
    @WebEndpoint(name = "IHelloWorldPort")
    public IHelloWorld getIHelloWorldPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.djel.cn/", "IHelloWorldPort"), IHelloWorld.class, features);
    }

}
